/* AUTH ACTIONS */
export const AUTH_STATE_BUSY = "AUTH_STATE_BUSY"
export const AUTH_STATE_FAILED = "AUTH_STATE_FAILED"
export const AUTH_STATE_SUCCESS = "AUTH_STATE_SUCCESS"

export const LOCATION_STATE_BUSY = "LOCATION_STATE_BUSY"
export const LOCATION_STATE_FAILED = "LOCATION_STATE_FAILED"
export const LOCATION_STATE_SUCCESS = "LOCATION_STATE_SUCCESS"

export const MYLOCATION_STATE_BUSY = "MYLOCATION_STATE_BUSY"
export const MYLOCATION_STATE_FAILED = "MYLOCATION_STATE_FAILED"
export const MYLOCATION_STATE_SUCCESS = "MYLOCATION_STATE_SUCCESS"
