/* AUTH ACTIONS */
export const AUTH_STATE_BUSY = "AUTH_STATE_BUSY"
export const AUTH_STATE_FAILED = "AUTH_STATE_FAILED"
export const AUTH_STATE_SUCCESS = "AUTH_STATE_SUCCESS"


export const LOCATION_STATE_BUSY = "LOCATION_STATE_BUSY"
export const LOCATION_STATE_FAILED = "LOCATION_STATE_FAILED"
export const LOCATION_STATE_SUCCESS = "LOCATION_STATE_SUCCESS"


export const MYLOCATION_STATE_BUSY = "MYLOCATION_STATE_BUSY"
export const MYLOCATION_STATE_FAILED = "MYLOCATION_STATE_FAILED"
export const MYLOCATION_STATE_SUCCESS = "MYLOCATION_STATE_SUCCESS"


export const CHECK_UNCHECK_STATE_BUSY = "CHECK_UNCHECK_STATE_BUSY"
export const CHECK_UNCHECK_STATE_FAILED = "CHECK_UNCHECK_STATE_FAILED"
export const CHECK_UNCHECK_STATE_SUCCESS = "CHECK_UNCHECK_STATE_SUCCESS"


export const CLEAR_MY_LOCATION_STATE_BUSY = "CLEAR_MY_LOCATION_STATE_BUSY"
export const CLEAR_MY_LOCATION_STATE_FAILED = "CLEAR_MY_LOCATION_STATE_FAILED"
export const CLEAR_MY_LOCATION_STATE_SUCCESS = "CLEAR_MY_LOCATION_STATE_SUCCESS"


export const PAYMENT_STATE_BUSY = "PAYMENT_STATE_BUSY"
export const PAYMENT_STATE_FAILED = "PAYMENT_STATE_FAILED"
export const PAYMENT_STATE_SUCCESS = "PAYMENT_STATE_SUCCESS"


/* AVAILABLE JOBS ACTIONS */

export const AVAILABLEJOB_STATE_BUSY = "AVAILABLEJOB_STATE_BUSY"
export const AVAILABLEJOB_STATE_FAILED = "AVAILABLEJOB_STATE_FAILED"
export const AVAILABLEJOB_STATE_SUCCESS = "AVAILABLEJOB_STATE_SUCCESS"
